version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: arthur-manifest_server_1
      APP_PORT: 1111

  server:
    image: ghcr.io/mnfst/manifest:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/data:/app/backend/db"