version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    container_name: arthur-manifest_app_proxy_1
    environment:
      APP_HOST: arthur-manifest_app_1
      APP_PORT: 2099

  app:
    image: manifestdotbuild/manifest:latest
    container_name: arthur-manifest_app_1
    init: true
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NODE_ENV: production
      PORT: 2099
      DATABASE_URL: "postgresql://manifest:${APP_PASSWORD}@arthur-manifest_db_1:5432/manifest"
      BETTER_AUTH_SECRET: "${APP_MANIFEST_BETTER_AUTH_SECRET}"
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    networks:
      default:
        aliases:
          - arthur-manifest_app_1

  db:
    image: postgres:16-alpine
    container_name: arthur-manifest_db_1
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: manifest
      POSTGRES_PASSWORD: "${APP_PASSWORD}"
      POSTGRES_DB: manifest
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${APP_DATA_DIR}/db:/var/lib/postgresql/data"
    networks:
      default:
        aliases:
          - arthur-manifest_db_1

networks:
  default:
    name: umbrel_main_network
    external: true